iaNetwork
activation
int iaNetwork::layersNumber
Referenced by iaNetwork, ForwardPropogation, BackwardPropogation, UpdateWeights, InitWeigths.
iaMatrix* iaNetwork::weights
Referenced by iaNetwork, ForwardPropogation, BackwardPropogation, UpdateWeights, InitWeigths.
iaLayer* iaNetwork::layers
Referenced by iaNetwork, ForwardPropogation, BackwardPropogation, UpdateWeights.
iaVector* iaNetwork::deltas
Referenced by iaNetwork, BackwardPropogation, UpdateWeights.
iaNetwork::iaNetwork()
iaNetwork::iaNetwork(int layersCount)
References layersNumber, weights, layers, deltas.
iaNetwork::iaNetwork(int layersCount, int sizes[])
References weights, layers, iaNetwork::iaLayer::x, iaNetwork::iaLayer::z, iaNetwork::iaLayer::fD, deltas.
iaNetwork::iaNetwork(netSetings setings)
iaNetwork::~iaNetwork()
iaVector iaNetwork::ForwardPropogation(iaVector inputVector, activation foncActiv)
References layersNumber, iaVector::sizeOfVector, layers, iaNetwork::iaLayer::x, iaNetwork::iaLayer::z, weights, iaMatrix::numberOfVectors, iaMatrix::sizeOfVectors, Hyperbolic_Tangent, iaNetwork::iaLayer::fD, Arctangent, Sigmoid, ReLu, Gaussian, Sin, Sinc.
Referenced by Train, main.
void iaNetwork::BackwardPropogation(iaVector outputVector, double *error)
References layersNumber, iaVector::sizeOfVector, layers, iaNetwork::iaLayer::z, deltas, iaNetwork::iaLayer::fD, weights, iaMatrix::sizeOfVectors, iaMatrix::numberOfVectors.
Referenced by Train.
void iaNetwork::UpdateWeights(double alpha)
References layersNumber, weights, iaMatrix::numberOfVectors, iaMatrix::sizeOfVectors, deltas, layers, iaNetwork::iaLayer::x.
Referenced by Train.
void iaNetwork::Train(iaMatrix X, iaMatrix Y, double alpha, double eps, int epochs)
References iaMatrix::numberOfVectors, ForwardPropogation, Gaussian, BackwardPropogation, UpdateWeights.
Referenced by main.
void iaNetwork::InitWeigths(iaMatrix newWeights)
References layersNumber, weights, iaMatrix::numberOfVectors, iaMatrix::sizeOfVectors.