iaMatrix
iaVector* iaMatrix::vector
Referenced by iaMatrix, printMatrix, operator[], operator&.
int iaMatrix::n
int iaMatrix::m
iaMatrix::iaMatrix()
iaMatrix::iaMatrix(int n)
iaMatrix::iaMatrix(int n, int m)
References vector.
iaMatrix::iaMatrix(int n, int m, const double values[])
References vector.
iaMatrix::iaMatrix(iaMatrix &otherMatrix)
References vector.
iaMatrix::~iaMatrix()
int iaMatrix::numberOfVectors()
Referenced by iaNetwork::ForwardPropogation, iaNetwork::BackwardPropogation, iaNetwork::UpdateWeights, iaNetwork::Train, iaNetwork::InitWeigths, iaMatrixTest.
int iaMatrix::sizeOfVectors()
Referenced by iaNetwork::ForwardPropogation, iaNetwork::BackwardPropogation, iaNetwork::UpdateWeights, iaNetwork::InitWeigths, iaMatrixTest.
void iaMatrix::printMatrix()
References vector.
Referenced by iaMatrixTest.
iaVector& iaMatrix::operator[](int i)
References vector.
iaVector* iaMatrix::operator&(int i)
References vector.