.TH "Содержание директории C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBDebug\fP"
.br
.ti -1c
.RI "директория \fBx64\fP"
.br
.in -1c
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBiaMatrix\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBiaMatrix\&.h\fP"
.br
.ti -1c
.RI "файл \fBiaNetwork\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBiaNetwork\&.h\fP"
.br
.ti -1c
.RI "файл \fBiaVector\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBiaVector\&.h\fP"
.br
.ti -1c
.RI "файл \fBneuro\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBtests\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBtests\&.h\fP"
.br
.in -1c
