.TH "Содержание директории C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/x64" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/x64
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBDebug\fP"
.br
.in -1c
