.TH "C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/iaMatrix.cpp" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/iaMatrix.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'iaMatrix\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
