.TH "C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/iaNetwork.h" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/iaNetwork.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <random>\fP
.br
\fC#include 'iaVector\&.h'\fP
.br
\fC#include 'iaMatrix\&.h'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBnetSetings\fP"
.br
.ti -1c
.RI "class \fBiaNetwork\fP"
.br
.ti -1c
.RI "struct \fBiaNetwork::iaLayer\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
