.TH "iaNetwork::iaLayer" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iaNetwork::iaLayer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iaNetwork\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBiaVector\fP \fBx\fP"
.br
.ti -1c
.RI "\fBiaVector\fP \fBz\fP"
.br
.ti -1c
.RI "\fBiaVector\fP \fBfD\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле iaNetwork\&.h строка 42
.SH "Данные класса"
.PP 
.SS "\fBiaVector\fP iaNetwork::iaLayer::fD"

.PP
См\&. определение в файле iaNetwork\&.h строка 46
.SS "\fBiaVector\fP iaNetwork::iaLayer::x"

.PP
См\&. определение в файле iaNetwork\&.h строка 44
.SS "\fBiaVector\fP iaNetwork::iaLayer::z"

.PP
См\&. определение в файле iaNetwork\&.h строка 45

.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
