.TH "iaVector" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iaVector
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iaVector\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBiaVector\fP ()"
.br
.ti -1c
.RI "\fBiaVector\fP (int m)"
.br
.ti -1c
.RI "\fBiaVector\fP (int m, const double values[])"
.br
.ti -1c
.RI "\fBiaVector\fP (\fBiaVector\fP &otherVector)"
.br
.ti -1c
.RI "\fB~iaVector\fP ()"
.br
.ti -1c
.RI "int \fBsizeOfVector\fP ()"
.br
.ti -1c
.RI "void \fBprintVector\fP ()"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (int j)"
.br
.ti -1c
.RI "double * \fBoperator&\fP (int j)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле iaVector\&.h строка 17
.SH "Конструктор(ы)"
.PP 
.SS "iaVector::iaVector ()"

.PP
См\&. определение в файле iaVector\&.cpp строка 15
.SS "iaVector::iaVector (int m)"

.PP
См\&. определение в файле iaVector\&.cpp строка 17
.SS "iaVector::iaVector (int m, const double values[])"

.PP
См\&. определение в файле iaVector\&.cpp строка 22
.SS "iaVector::iaVector (\fBiaVector\fP & otherVector)"

.PP
См\&. определение в файле iaVector\&.cpp строка 26
.SS "iaVector::~iaVector ()"

.PP
См\&. определение в файле iaVector\&.cpp строка 28
.SH "Методы"
.PP 
.SS "double* iaVector::operator& (int j)\fC [inline]\fP"

.PP
См\&. определение в файле iaVector\&.h строка 32
.SS "double& iaVector::operator[] (int j)\fC [inline]\fP"

.PP
См\&. определение в файле iaVector\&.h строка 31
.SS "void iaVector::printVector ()"

.PP
См\&. определение в файле iaVector\&.cpp строка 34
.SS "int iaVector::sizeOfVector ()"

.PP
См\&. определение в файле iaVector\&.cpp строка 30

.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
