.TH "netSetings" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netSetings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iaNetwork\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBnetSetings\fP ()"
.br
.ti -1c
.RI "\fBnetSetings\fP (int n)"
.br
.ti -1c
.RI "\fBnetSetings\fP (int n, int s[])"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "int \fBnumberOfLayers\fP"
.br
.ti -1c
.RI "int * \fBsizes\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле iaNetwork\&.h строка 11
.SH "Конструктор(ы)"
.PP 
.SS "netSetings::netSetings ()\fC [inline]\fP"

.PP
См\&. определение в файле iaNetwork\&.h строка 13
.SS "netSetings::netSetings (int n)\fC [inline]\fP"

.PP
См\&. определение в файле iaNetwork\&.h строка 15
.SS "netSetings::netSetings (int n, int s[])\fC [inline]\fP"

.PP
См\&. определение в файле iaNetwork\&.h строка 20
.SH "Данные класса"
.PP 
.SS "int netSetings::numberOfLayers"

.PP
См\&. определение в файле iaNetwork\&.h строка 24
.SS "int* netSetings::sizes"

.PP
См\&. определение в файле iaNetwork\&.h строка 25

.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
