.TH "C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/neuro.cpp" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/neuro.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <random>\fP
.br
\fC#include 'iaVector\&.h'\fP
.br
\fC#include 'iaMatrix\&.h'\fP
.br
\fC#include 'iaNetwork\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main ()"

.PP
См\&. определение в файле neuro\&.cpp строка 27
.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
