.TH "C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/setings.txt" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/setings.txt
.SH SYNOPSIS
.br
.PP
.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
