.TH "C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/tests.cpp" 3 "Сб 6 Ноя 2021" "Neuro Net" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/aleksandri/Documents/GitHub/NeuroNet_education_/tests.cpp
.SH SYNOPSIS
.br
.PP
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBiaVectorTest\fP ()"
.br
.ti -1c
.RI "void \fBiaMatrixTest\fP ()"
.br
.ti -1c
.RI "void \fBiaNetworkTest\fP ()"
.br
.in -1c
.SH "Функции"
.PP 
.SS "void iaMatrixTest ()"

.PP
См\&. определение в файле tests\&.cpp строка 33
.SS "void iaNetworkTest ()"

.PP
См\&. определение в файле tests\&.cpp строка 71
.SS "void iaVectorTest ()"

.PP
См\&. определение в файле tests\&.cpp строка 1
.SH "Автор"
.PP 
Автоматически создано Doxygen для Neuro Net из исходного текста\&.
